services:
  - type: web
    name: api-gateway
    env: docker
    dockerfilePath: ./api-gateway/Dockerfile
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: lms-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: lms-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: lms-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: lms-db
          property: password

databases:
  - name: lms-db
    plan: free
