server:
  port: ${PORT:8761}

spring:
  application:
    name: discovery-server
  main:
    lazy-initialization: true  # Faster startup time
    banner-mode: off  # Reduce startup output

eureka:
  instance:
    hostname: ${RENDER_EXTERNAL_HOSTNAME:localhost}
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${RENDER_INSTANCE_ID:${random.value}}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
    peer-node-read-timeout-ms: 1000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.context.support.PostProcessorRegistrationDelegate: ERROR
    org.springframework.cloud.loadbalancer: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
